[workspace]
resolver = "2"
members = [
    "crates/slk-protocol",
    "crates/libsparklink",
    "crates/slkd",
    "crates/slkconfig",
    "crates/slctl",
    "crates/slkmon",
    "crates/slkdump",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://gitee.com/sparklinkZ/sparklink-userspace"

[workspace.dependencies]
slk-protocol = { path = "crates/slk-protocol" }
libsparklink = { path = "crates/libsparklink" }
tokio = { version = "1", features = ["full"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
nix = { version = "0.30", features = ["ioctl", "fs", "net"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-journald = "0.3"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
rustyline = "15"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
