#ifndef SPARKLINK_H
#define SPARKLINK_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdint.h>
#define SPARKLINK_ALIGN(n) __attribute__((aligned(n)))

/**
 * C header array bound, checked against the canonical protocol declaration.
 */
#define CONTROLLER_EVENT_PAYLOAD_MAX 288

/**
 * C header array bound, checked against the canonical protocol declaration.
 */
#define SNOOP_PAYLOAD_MAX 320

#define WS73_BASIC_POLICY_VERSION 1

/**
 * Opaque adapter handle for C consumers
 */
typedef struct SlkAdapter SlkAdapter;

/**
 * Scan parameters (ioctl 0x12)
 */
typedef struct SleScanParams {
    uint16_t dev_index;
    uint16_t window_ms;
    uint16_t interval_ms;
    uint8_t filter_discovery_level;
    uint8_t _reserved[9];
} SleScanParams;

/**
 * MAC address (6 bytes)
 */
typedef uint8_t SleAddr[6];

/**
 * Connection parameters (ioctl 0x30)
 */
typedef struct SleConnectParams {
    SleAddr peer_addr;
    uint8_t gt_role;
    uint8_t bandwidth;
    uint8_t mcs_index;
    uint8_t _pad;
    uint16_t timeout_10ms;
    uint8_t _reserved[4];
} SleConnectParams;

/**
 * Connection info (ioctl 0x32)
 */
typedef struct SleConnInfo {
    uint64_t tx_bytes;
    uint64_t rx_bytes;
    uint16_t handle;
    uint16_t event_group_period;
    uint16_t supervision_timeout;
    uint16_t tx_pending;
    uint16_t rx_pending;
    uint8_t state;
    SleAddr peer_addr;
    uint8_t local_role;
    uint8_t bandwidth_mhz;
    uint8_t mcs_index;
    uint8_t tx_seq;
    uint8_t rx_seq;
    uint16_t data_mtu;
    uint16_t data_mps;
    uint16_t svc_mtu;
    uint8_t data_mode;
    uint8_t ssap_info_exchanged;
    uint16_t ssap_mtu;
    uint8_t ssap_reliable_mode;
    uint8_t ssap_version_major;
    uint16_t smtc_tx_credits;
    uint16_t smtc_rx_credits;
    uint16_t dudtc_tx_credits;
    uint16_t dudtc_rx_credits;
} SleConnInfo;

/**
 * Security info (ioctl 0x42)
 */
typedef struct SleSecInfo {
    uint8_t state;
    uint8_t method;
    uint8_t mode;
    uint8_t enc_enabled;
    uint8_t enc_key_fingerprint[4];
    uint8_t _reserved[8];
} SleSecInfo;

/**
 * Pair params (ioctl 0x41)
 */
typedef struct SlePairParams {
    uint8_t method;
    uint8_t _reserved[3];
} SlePairParams;

/**
 * SSAP summary (ioctl 0x51)
 */
typedef struct SsapSummary {
    uint16_t service_count;
    uint16_t property_count;
    uint16_t total_entries;
    uint16_t mtu;
    uint16_t notification_count;
    uint8_t _reserved[6];
} SsapSummary;

/**
 * SSAP read/write (ioctl 0x52/0x53)
 */
typedef struct SsapReadWrite {
    uint16_t handle;
    uint16_t length;
    uint8_t data[252];
} SsapReadWrite;

/**
 * DLI event (ioctl 0x82)
 */
typedef struct SleDliEvent {
    uint8_t event_type;
    uint8_t status;
    uint16_t handle;
    uint16_t opcode;
    uint16_t data_len;
    uint8_t data[240];
    SleAddr addr;
    uint8_t _pad[2];
} SleDliEvent;

/**
 * Device information (ioctl 0x04)
 */
typedef struct SciDevInfo {
    uint16_t index;
    uint8_t state;
    uint8_t bus;
    SleAddr addr;
    uint8_t name[32];
    uint8_t _reserved[24];
} SciDevInfo;

/**
 * DLI controller info (ioctl 0x80)
 */
typedef struct SleDliInfo {
    uint8_t bus;
    uint8_t _pad[3];
    uint32_t firmware_version;
    uint64_t features;
    uint8_t max_connections;
    uint8_t max_adv_sets;
    uint8_t transport_modes;
    uint8_t measurement_cap;
    uint16_t max_mtu;
    uint16_t max_mps;
    uint16_t security_cap;
    uint16_t features_ext;
    uint8_t name[32];
    uint8_t _reserved[4];
} SleDliInfo;

/**
 * PHY info (ioctl 0x90)
 */
typedef struct SlePhyInfo {
    uint8_t mcs_index;
    uint8_t bandwidth_mhz;
    uint8_t pilot_density;
    int8_t tx_power_dbm;
    uint8_t mimo_mode;
    uint8_t num_tx_ant;
    uint8_t num_rx_ant;
    uint8_t ofdm;
    uint32_t data_rate_kbps;
    uint8_t hop_channel;
    uint8_t hop_increment;
    uint8_t hop_used_channels;
    uint8_t _pad;
    uint8_t modulation;
    uint8_t code_rate_num;
    uint8_t code_rate_den;
    uint8_t _reserved[5];
} SlePhyInfo;

/**
 * Selected registration metadata and Host readiness, independent of RF state.
 * FULL_METADATA marks the queried native five-byte version/80-bit features.
 */
typedef struct SPARKLINK_ALIGN(8) SleControllerSnapshot {
    uint64_t generation;
    uint32_t version;
    uint32_t flags;
    uint32_t profile;
    uint32_t valid_fields;
    uint16_t dev_index;
    uint8_t bus;
    uint8_t command_credits;
    uint16_t acb_length;
    uint16_t icb_length;
    uint8_t acb_count;
    uint8_t icb_count;
    uint8_t version_tuple[5];
    uint8_t features[10];
    uint8_t address[6];
    uint8_t reserved_byte;
    int32_t error;
    uint8_t reserved[4];
} SleControllerSnapshot;

typedef struct SPARKLINK_ALIGN(8) SleManagementQuery {
    uint64_t generation;
    uint64_t lease;
    uint32_t version;
    uint32_t mode;
    uint32_t state;
    uint32_t flags;
    int32_t error;
    uint32_t status;
    uint32_t opcode;
    uint32_t reserved;
} SleManagementQuery;

typedef struct SleDiscoveryAdvConfig {
    uint32_t handle;
    uint32_t mode;
    uint32_t gt_role;
    uint32_t interval_min;
    uint32_t interval_max;
    uint32_t channel_map;
    uint32_t own_address_type;
    uint32_t peer_address_type;
    uint8_t own_address[6];
    uint8_t peer_address[6];
    uint32_t filter;
    int32_t tx_power;
    uint32_t primary_frame;
    uint32_t secondary_frame;
    uint32_t secondary_phy;
    uint32_t secondary_pilot;
    uint32_t secondary_mcs;
    uint32_t secondary_max_skip;
    uint32_t sid;
    uint32_t request_notification;
    uint32_t max_requests;
    uint32_t request_rx_duration;
    uint32_t conn_interval_min;
    uint32_t conn_interval_max;
    uint32_t conn_max_latency;
    uint32_t supervision_timeout;
    uint32_t min_event_length;
    uint32_t max_event_length;
} SleDiscoveryAdvConfig;

typedef struct SleDiscoveryScanConfig {
    uint32_t own_address_type;
    uint32_t filter;
    uint32_t frame_types;
    uint32_t active;
    uint32_t interval;
    uint32_t window;
    uint32_t filter_duplicates;
} SleDiscoveryScanConfig;

typedef struct SPARKLINK_ALIGN(8) SleDiscoverySubmit {
    uint32_t version;
    uint32_t profile;
    uint32_t operation;
    uint32_t flags;
    uint64_t generation;
    uint64_t request_id;
    struct SleDiscoveryAdvConfig advertising;
    struct SleDiscoveryScanConfig scanning;
    uint32_t handle;
    uint32_t duration;
    uint32_t max_events;
    uint32_t data_len;
    uint32_t scan_response_len;
    uint32_t reserved;
    uint8_t data[251];
    uint8_t scan_response[251];
    uint8_t reserved_tail[2];
} SleDiscoverySubmit;

typedef struct SPARKLINK_ALIGN(8) SleDiscoveryResult {
    uint64_t generation;
    uint64_t request_id;
    uint32_t version;
    uint32_t flags;
    uint32_t profile;
    uint32_t operation;
    uint32_t state;
    int32_t error;
    int32_t selected_power;
    uint32_t radio_adv;
    uint32_t radio_scan;
    uint16_t dev_index;
    uint16_t opcode;
    uint8_t step;
    uint8_t count;
    uint8_t status;
    uint8_t power_valid;
    uint8_t reserved[4];
} SleDiscoveryResult;

/**
 * Complete, validated controller parameters from one registration.
 * Sequence and loss counts belong to that registration and reader cursor.
 */
typedef struct SPARKLINK_ALIGN(8) SleControllerEvent {
    uint64_t seq;
    uint64_t generation;
    /**
     * CLOCK_BOOTTIME receipt timestamp, in nanoseconds.
     */
    uint64_t timestamp_ns;
    uint64_t lost;
    uint32_t profile;
    uint16_t dev_index;
    uint16_t event_code;
    uint16_t payload_len;
    uint16_t flags;
    uint32_t _reserved;
    uint8_t payload[CONTROLLER_EVENT_PAYLOAD_MAX];
} SleControllerEvent;

/**
 * Input cursor/version with an output-only event record (ioctl 0x87).
 */
typedef struct SPARKLINK_ALIGN(8) SleControllerEventQuery {
    uint64_t after_seq;
    uint64_t generation;
    uint32_t version;
    uint32_t flags;
    struct SleControllerEvent event;
} SleControllerEventQuery;

typedef struct SPARKLINK_ALIGN(8) SleSnoopRecord {
    uint64_t seq;
    uint64_t generation;
    uint64_t timestamp_ns;
    uint64_t lost;
    uint32_t profile;
    uint32_t original_length;
    int32_t status;
    uint16_t dev_index;
    uint8_t direction;
    uint8_t format;
    uint16_t captured_length;
    uint16_t flags;
    uint32_t reserved;
    uint8_t payload[SNOOP_PAYLOAD_MAX];
} SleSnoopRecord;

typedef struct SPARKLINK_ALIGN(8) SleSnoopQuery {
    uint64_t generation;
    uint64_t after_seq;
    uint32_t version;
    uint32_t flags;
    uint64_t reserved;
    struct SleSnoopRecord record;
} SleSnoopQuery;

/**
 * Final successful matched Complete receipt (CLOCK_BOOTTIME ns).
 * Pending, failed/cancelled/faulted without success have timestamp zero.
 */
typedef struct SPARKLINK_ALIGN(8) SleDiscoveryTiming {
    uint64_t generation;
    uint64_t request_id;
    uint64_t completed_boottime_ns;
    uint32_t version;
    uint32_t flags;
    uint32_t operation;
    uint32_t state;
    uint16_t dev_index;
    uint16_t opcode;
    uint8_t status;
    uint8_t reserved[3];
} SleDiscoveryTiming;

/**
 * Owner-private non-destructive diagnostic result (ioctl 0xd0).
 */
typedef struct SPARKLINK_ALIGN(8) SleDiagnosticResult {
    uint32_t version;
    uint32_t flags;
    uint64_t generation;
    uint32_t seq;
    uint32_t state;
    int32_t error;
    uint16_t opcode;
    uint8_t status;
    uint8_t _pad;
    uint16_t data_len;
    uint8_t _reserved[6];
    uint8_t data[64];
} SleDiagnosticResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open a SparkLink adapter device.
 * Returns null on failure.
 *
 * # Safety
 * `dev_path` must be a valid null-terminated C string.
 */
struct SlkAdapter *slk_adapter_open(const char *dev_path);

/**
 * Free an adapter handle.
 *
 * # Safety
 * `adapter` must be a valid pointer returned by `slk_adapter_open`, or null.
 */
void slk_adapter_free(struct SlkAdapter *adapter);

/**
 * Get the device count.
 * Returns -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_device_count(const struct SlkAdapter *adapter);

/**
 * Start scanning.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 * `params` must point to a valid `SleScanParams` struct.
 */
int slk_start_scan(const struct SlkAdapter *adapter, const struct SleScanParams *params);

/**
 * Stop scanning.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_stop_scan(const struct SlkAdapter *adapter);

/**
 * Initiate a connection.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 * `params` must point to a valid `SleConnectParams` struct.
 */
int slk_connect(const struct SlkAdapter *adapter, const struct SleConnectParams *params);

/**
 * Disconnect a connection by handle.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_disconnect(const struct SlkAdapter *adapter, uint16_t handle);

/**
 * Get connection info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_conn_info(const struct SlkAdapter *adapter, uint16_t handle, struct SleConnInfo *out);

/**
 * Get security info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_sec_info(const struct SlkAdapter *adapter, struct SleSecInfo *out);

/**
 * Initiate pairing.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `params` must be valid non-null pointers.
 */
int slk_pair(const struct SlkAdapter *adapter, const struct SlePairParams *params);

/**
 * Enable encryption.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_encrypt_on(const struct SlkAdapter *adapter);

/**
 * Get SSAP summary.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_ssap_info(const struct SlkAdapter *adapter, struct SsapSummary *out);

/**
 * Read an SSAP property.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_ssap_read(const struct SlkAdapter *adapter, uint16_t handle, struct SsapReadWrite *out);

/**
 * Write an SSAP property.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `data` must be valid non-null pointers.
 */
int slk_ssap_write(const struct SlkAdapter *adapter, const struct SsapReadWrite *data);

/**
 * Poll for a DLI event (non-blocking).
 * Returns 1 if event available (written to `out`), 0 if no event, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_poll_event(const struct SlkAdapter *adapter, struct SleDliEvent *out);

/**
 * Get device info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_device_info(const struct SlkAdapter *adapter, struct SciDevInfo *out);

/**
 * Get DLI controller info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_dli_info(const struct SlkAdapter *adapter, struct SleDliInfo *out);

/**
 * Get PHY info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_phy_info(const struct SlkAdapter *adapter, struct SlePhyInfo *out);

/**
 * Set device role (0 = G-node, 1 = T-node).
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_set_role(const struct SlkAdapter *adapter, uint8_t role);

/**
 * Get device role.
 * Returns role (0 or 1) on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_get_role(const struct SlkAdapter *adapter);

/**
 * Invoke a method on a remote peer's SSAP service.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 * `input` must point to `input_len` readable bytes.
 * `output` must point to `output_len` writable bytes.
 * On success, `output_len` is updated with the actual output size.
 */
int slk_ssap_call_method(const struct SlkAdapter *adapter,
                         uint16_t conn_handle,
                         uint16_t method_handle,
                         const uint8_t *input,
                         uintptr_t input_len,
                         uint8_t *output,
                         uintptr_t *output_len);

/**
 * Find a remote service by UUID.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 * Use `uuid16` for 16-bit UUIDs or `uuid128` for 128-bit UUIDs (set uuid16=0).
 * On success, `out_handle` receives the matched service handle.
 */
int slk_ssap_find_by_uuid(const struct SlkAdapter *adapter,
                          uint16_t conn_handle,
                          uint16_t uuid16,
                          const uint8_t *uuid128,
                          uint16_t *out_handle);

/**
 * Read a remote property by UUID.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 * `output` must point to `output_len` writable bytes.
 * On success, `output_len` is updated with the actual data size.
 */
int slk_ssap_read_by_uuid(const struct SlkAdapter *adapter,
                          uint16_t conn_handle,
                          uint16_t uuid16,
                          const uint8_t *uuid128,
                          uint8_t *output,
                          uintptr_t *output_len);

/**
 * Bind this fd to one registration, without changing legacy global selection.
 * Returns 0 or negative errno. Replug invalidates this fd; open a new handle.
 * # Safety
 * `adapter` is null or a live, exclusively borrowed adapter handle.
 */
int slk_adapter_select(struct SlkAdapter *adapter, uint16_t index);

/**
 * Borrow this handle's fd for poll/epoll; never close it or change its affinity.
 * Activate controller-event/snoop mode with its poll function BEFORE adding
 * this fd to poll/epoll. Use separately opened handles for independent readers.
 * # Safety
 * `adapter` is null or a live handle. Its fd remains valid only until free.
 */
int slk_adapter_fd(const struct SlkAdapter *adapter);

/**
 * Return the registered index bitmap (indices can have holes), or -errno.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; out is writable.
 */
int slk_device_mask(const struct SlkAdapter *adapter, uint16_t *out);

/**
 * Query selected registration metadata. generation=0 probes; otherwise exact.
 * This observes Host readiness; it does not enable a radio domain.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; out is writable.
 */
int slk_controller_snapshot(const struct SlkAdapter *adapter,
                            uint64_t generation,
                            struct SleControllerSnapshot *out);

/**
 * Acquire Managed(1) or Diagnostic(2) on this exact generation/fd. Kernel
 * CAP_NET_ADMIN and ownership checks apply; a lease alone grants no authority.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; lease is writable.
 */
int slk_management_acquire(const struct SlkAdapter *adapter,
                           uint64_t generation,
                           uint32_t mode,
                           uint64_t *lease);

/**
 * Observe selected ownership. generation=0 probes; another fd sees no token.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; out is writable.
 */
int slk_management_query(const struct SlkAdapter *adapter,
                         uint64_t generation,
                         struct SleManagementQuery *out);

/**
 * Request asynchronous release. Success is admission, not completed cleanup;
 * query ownership until Free before treating a successor as available.
 * # Safety
 * `adapter` is null or a live handle with no concurrent free/selection.
 */
int slk_management_release(const struct SlkAdapter *adapter,
                           uint64_t generation,
                           uint64_t lease,
                           uint32_t mode);

/**
 * Submit all typed discovery parameters using Managed ownership. Return 0
 * means admission only; result state/status/error determine actual completion.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; request is readable.
 */
int slk_discovery_submit(const struct SlkAdapter *adapter,
                         const struct SleDiscoverySubmit *request);

/**
 * Non-consuming result: 1 record, 0 absent/evicted, negative errno. A record
 * may still be queued/pending; failed terminal records retain raw reasons.
 * Output is unchanged on 0/error. Generation/request must both be nonzero.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; out is writable.
 */
int slk_discovery_result(const struct SlkAdapter *adapter,
                         uint64_t generation,
                         uint64_t request_id,
                         struct SleDiscoveryResult *out);

/**
 * Independent complete controller event: 1 record, 0 quiet, negative errno.
 * Initialize query to zero with version=1 and explicit nonzero generation.
 * Success advances after_seq; quiet/error leaves all caller bytes unchanged.
 * No raw legacy fallback. Event and snoop modes on one fd cannot be mixed.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; query is read/write.
 */
int slk_controller_event(const struct SlkAdapter *adapter, struct SleControllerEventQuery *query);

/**
 * Privileged independent DLI seam observation: 1 record, 0 quiet, -errno.
 * Initialize zero query with version=1 and explicit generation. Success alone
 * advances after_seq. CAP_NET_ADMIN applies on every call; never takes a lease
 * or consumes Host raw replies. Use a separate selected observation handle.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; query is read/write.
 */
int slk_snoop(const struct SlkAdapter *adapter, struct SleSnoopQuery *query);

/**
 * Query final matched Complete receipt (CLOCK_BOOTTIME ns), 0 or -errno.
 * Pending/non-success timing is zero; output remains untouched on failure.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; out is writable.
 */
int slk_discovery_timing(const struct SlkAdapter *adapter,
                         uint64_t generation,
                         uint64_t request_id,
                         struct SleDiscoveryTiming *out);

/**
 * Query the originating fd's raw diagnostic result, without consuming events.
 * Returns 1 present, 0 absent/evicted or -errno; failed queries leave out intact.
 * Requires an exact generation, nonzero seq and Diagnostic ownership/admin.
 * # Safety
 * Non-null pointers are valid, aligned, nonoverlapping; out is writable.
 */
int slk_diagnostic_result(const struct SlkAdapter *adapter,
                          uint64_t generation,
                          uint32_t seq,
                          struct SleDiagnosticResult *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SPARKLINK_H */
