#ifndef SPARKLINK_H
#define SPARKLINK_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque adapter handle for C consumers
 */
typedef struct SlkAdapter SlkAdapter;

/**
 * Scan parameters (ioctl 0x12)
 */
typedef struct SleScanParams {
    uint16_t dev_index;
    uint16_t window_ms;
    uint16_t interval_ms;
    uint8_t filter_discovery_level;
    uint8_t _reserved[9];
} SleScanParams;

/**
 * MAC address (6 bytes)
 */
typedef uint8_t SleAddr[6];

/**
 * Connection parameters (ioctl 0x30)
 */
typedef struct SleConnectParams {
    SleAddr peer_addr;
    uint8_t gt_role;
    uint8_t bandwidth;
    uint8_t mcs_index;
    uint8_t _pad;
    uint16_t timeout_10ms;
    uint8_t _reserved[4];
} SleConnectParams;

/**
 * Connection info (ioctl 0x32)
 */
typedef struct SleConnInfo {
    uint64_t tx_bytes;
    uint64_t rx_bytes;
    uint16_t handle;
    uint16_t event_group_period;
    uint16_t supervision_timeout;
    uint16_t tx_pending;
    uint16_t rx_pending;
    uint8_t state;
    SleAddr peer_addr;
    uint8_t local_role;
    uint8_t bandwidth_mhz;
    uint8_t mcs_index;
    uint8_t tx_seq;
    uint8_t rx_seq;
    uint16_t data_mtu;
    uint16_t data_mps;
    uint16_t svc_mtu;
    uint8_t data_mode;
    uint8_t ssap_info_exchanged;
    uint16_t ssap_mtu;
    uint16_t smtc_tx_credits;
    uint16_t smtc_rx_credits;
    uint16_t dudtc_tx_credits;
    uint16_t dudtc_rx_credits;
} SleConnInfo;

/**
 * Security info (ioctl 0x42)
 */
typedef struct SleSecInfo {
    uint8_t state;
    uint8_t method;
    uint8_t mode;
    uint8_t enc_enabled;
    uint8_t enc_key_fingerprint[4];
    uint8_t _reserved[8];
} SleSecInfo;

/**
 * Pair params (ioctl 0x41)
 */
typedef struct SlePairParams {
    uint8_t method;
    uint8_t _reserved[3];
} SlePairParams;

/**
 * SSAP summary (ioctl 0x51)
 */
typedef struct SsapSummary {
    uint16_t service_count;
    uint16_t property_count;
    uint16_t total_entries;
    uint16_t mtu;
    uint16_t notification_count;
    uint8_t _reserved[6];
} SsapSummary;

/**
 * SSAP read/write (ioctl 0x52/0x53)
 */
typedef struct SsapReadWrite {
    uint16_t handle;
    uint16_t length;
    uint8_t data[252];
} SsapReadWrite;

/**
 * DLI event (ioctl 0x82)
 */
typedef struct SleDliEvent {
    uint8_t event_type;
    uint8_t status;
    uint16_t handle;
    uint16_t opcode;
    uint16_t data_len;
    uint8_t data[240];
    SleAddr addr;
    uint8_t _pad[2];
} SleDliEvent;

/**
 * Device information (ioctl 0x04)
 */
typedef struct SciDevInfo {
    uint16_t index;
    uint8_t state;
    uint8_t bus;
    SleAddr addr;
    uint8_t name[32];
    uint8_t _reserved[24];
} SciDevInfo;

/**
 * DLI controller info (ioctl 0x80)
 */
typedef struct SleDliInfo {
    uint8_t bus;
    uint8_t _pad[3];
    uint32_t firmware_version;
    uint64_t features;
    uint8_t max_connections;
    uint8_t max_adv_sets;
    uint8_t transport_modes;
    uint8_t measurement_cap;
    uint16_t max_mtu;
    uint16_t max_mps;
    uint8_t security_cap;
    uint8_t features_ext;
    uint8_t name[32];
    uint8_t _reserved[4];
} SleDliInfo;

/**
 * PHY info (ioctl 0x90)
 */
typedef struct SlePhyInfo {
    uint8_t mcs_index;
    uint8_t bandwidth_mhz;
    uint8_t pilot_density;
    int8_t tx_power_dbm;
    uint8_t mimo_mode;
    uint8_t num_tx_ant;
    uint8_t num_rx_ant;
    uint8_t ofdm;
    uint32_t data_rate_kbps;
    uint8_t hop_channel;
    uint8_t hop_increment;
    uint8_t hop_used_channels;
    uint8_t _pad;
    uint8_t modulation;
    uint8_t code_rate_num;
    uint8_t code_rate_den;
    uint8_t _reserved[5];
} SlePhyInfo;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open a SparkLink adapter device.
 * Returns null on failure.
 *
 * # Safety
 * `dev_path` must be a valid null-terminated C string.
 */
struct SlkAdapter *slk_adapter_open(const char *dev_path);

/**
 * Free an adapter handle.
 *
 * # Safety
 * `adapter` must be a valid pointer returned by `slk_adapter_open`, or null.
 */
void slk_adapter_free(struct SlkAdapter *adapter);

/**
 * Get the device count.
 * Returns -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_device_count(const struct SlkAdapter *adapter);

/**
 * Start scanning.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 * `params` must point to a valid `SleScanParams` struct.
 */
int slk_start_scan(const struct SlkAdapter *adapter, const struct SleScanParams *params);

/**
 * Stop scanning.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_stop_scan(const struct SlkAdapter *adapter);

/**
 * Initiate a connection.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 * `params` must point to a valid `SleConnectParams` struct.
 */
int slk_connect(const struct SlkAdapter *adapter, const struct SleConnectParams *params);

/**
 * Disconnect a connection by handle.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_disconnect(const struct SlkAdapter *adapter, uint16_t handle);

/**
 * Get connection info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_conn_info(const struct SlkAdapter *adapter, uint16_t handle, struct SleConnInfo *out);

/**
 * Get security info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_sec_info(const struct SlkAdapter *adapter, struct SleSecInfo *out);

/**
 * Initiate pairing.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `params` must be valid non-null pointers.
 */
int slk_pair(const struct SlkAdapter *adapter, const struct SlePairParams *params);

/**
 * Enable encryption.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_encrypt_on(const struct SlkAdapter *adapter);

/**
 * Get SSAP summary.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_ssap_info(const struct SlkAdapter *adapter, struct SsapSummary *out);

/**
 * Read an SSAP property.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_ssap_read(const struct SlkAdapter *adapter, uint16_t handle, struct SsapReadWrite *out);

/**
 * Write an SSAP property.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `data` must be valid non-null pointers.
 */
int slk_ssap_write(const struct SlkAdapter *adapter, const struct SsapReadWrite *data);

/**
 * Poll for a DLI event (non-blocking).
 * Returns 1 if event available (written to `out`), 0 if no event, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_poll_event(const struct SlkAdapter *adapter, struct SleDliEvent *out);

/**
 * Get device info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_device_info(const struct SlkAdapter *adapter, struct SciDevInfo *out);

/**
 * Get DLI controller info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_dli_info(const struct SlkAdapter *adapter, struct SleDliInfo *out);

/**
 * Get PHY info.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` and `out` must be valid non-null pointers.
 */
int slk_phy_info(const struct SlkAdapter *adapter, struct SlePhyInfo *out);

/**
 * Set device role (0 = G-node, 1 = T-node).
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_set_role(const struct SlkAdapter *adapter, uint8_t role);

/**
 * Get device role.
 * Returns role (0 or 1) on success, -1 on error.
 *
 * # Safety
 * `adapter` must be a valid non-null pointer.
 */
int slk_get_role(const struct SlkAdapter *adapter);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SPARKLINK_H */
