[package]
name = "slkconfig"
description = "SparkLink offline configuration tool"
version.workspace = true
edition.workspace = true

[[bin]]
name = "slkconfig"
path = "src/main.rs"

[dependencies]
anyhow = "1"
slk-protocol = { workspace = true }
libsparklink = { workspace = true }
clap = { workspace = true }
